name: tofu
description: "강아지 산책 앱 - Dog Walking App"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # 위치
  geolocator: ^13.0.2

  # 상태 관리
  provider: ^6.1.2

  # 유틸리티
  intl: ^0.19.0

  # 권한 관리
  permission_handler: ^11.3.1

  # 로컬 저장
  shared_preferences: ^2.3.2

  # 차트
  fl_chart: ^0.69.0

  # 이미지 선택
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
