<<<<<<< Updated upstream
name: test_project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
=======
name: tofu
description: "강아지 산책 앱 - Dog Walking App"
publish_to: "none"
>>>>>>> Stashed changes

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

<<<<<<< Updated upstream

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

=======
  cupertino_icons: ^1.0.8

  # 위치 및 지도
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.0

  # 상태 관리
  provider: ^6.1.2

  # 유틸리티
  intl: ^0.19.0

  # 권한 관리
  permission_handler: ^11.3.1

  # 로컬 저장
  shared_preferences: ^2.3.2

  # 차트
  fl_chart: ^0.69.0

  # 이미지 선택
  image_picker: ^1.1.2

>>>>>>> Stashed changes
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
<<<<<<< Updated upstream

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
=======
>>>>>>> Stashed changes
  uses-material-design: true
